menuya/delivery/urls.py
from django.urls import path

from . import views

app_name = 'delivery'

urlpatterns = [
    path('',views.index,name='index'),
    path('<int:plato_id>',views.plato,name='plato'),
    path('agregarCarrito/<int:plato_id>',views.agregarCarrito,name='agregarCarrito'),
    path('carrito',views.mostrarCarrito,name='carrito'),
    path('eliminarCarrito/<int:plato_id>',views.eliminarPlatoCarrito,name='eliminarCarrito'),
    path('limpiarCarrito',views.limpiarCarrito,name='limpiarCarrito'),
    path('login',views.loginUsuario,name='login'),
    path('registro',views.registroCliente,name='registro'),
    path('pedido',views.registrarPedido,name='pedido'),
    path('gracias',views.gracias,name='gracias'),
    path('confirmarPedido',views.confirmarPedido,name='confirmarPedido')
]

menuya/menuya/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('delivery/',include('delivery.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

menuya/delivery/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Negocio(models.Model):
    nombre = models.CharField(max_length=200)
    imagen = models.ImageField(upload_to='negocios',blank=True,null=True)
    telefono = models.CharField(max_length=50,default='')
    precioEnvio = models.DecimalField(max_digits=9,decimal_places=2)
    calificacion = models.IntegerField(default=0)
    
    def __str__(self):
        return self.nombre
    
class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    imagen = models.ImageField(upload_to='categorias',blank=True,null=True)
    
    def __str__(self):
        return self.nombre
    
class Plato(models.Model):
    categoria = models.ForeignKey(Categoria,on_delete=models.RESTRICT)
    nombre = models.CharField(max_length=200)
    descripcion = models.TextField()
    imagen = models.ImageField(upload_to='platos',blank=True,null=True)
    precio = models.DecimalField(max_digits=9,decimal_places=2)
    negocio = models.ForeignKey(Negocio,on_delete=models.RESTRICT)
    
    def __str__(self):
        return self.nombre
    
class FormaPago(models.Model):
    nombre = models.CharField(max_length=200)
    
    def __str__(self):
        return self.nombre
    
class Cliente(models.Model):
    usuario = models.OneToOneField(User,on_delete=models.RESTRICT)
    telefono = models.CharField(max_length=20)
    
    def __str__(self):
        return self.telefono
    
class Pedido(models.Model):
    cliente = models.ForeignKey(Cliente,on_delete=models.RESTRICT)
    direccion = models.CharField(max_length=200)
    fechaHora = models.DateTimeField(auto_now=True)
    formaPago = models.ForeignKey(FormaPago,on_delete=models.RESTRICT)
    totalPagar = models.DecimalField(max_digits=9,decimal_places=2)
    montoPago = models.DecimalField(max_digits=20,decimal_places=2)
    
    def __str__(self):
        return str(self.fechaHora)
    
class PedidoDetalle(models.Model):
    pedido = models.ForeignKey(Pedido,on_delete=models.RESTRICT)
    plato = models.ForeignKey(Plato,on_delete=models.RESTRICT)
    precio = models.DecimalField(max_digits=9,decimal_places=2)
    cantidad = models.IntegerField(default=1)
    
    def __str__(self):
        return self.plato.nombre
    
    
    



    

    
    

menuya/delivery/views.py
from django.shortcuts import render,redirect

from .models import Categoria,Plato,Negocio,Cliente,FormaPago,Pedido,PedidoDetalle

# Create your views here.
def index(request):
    lstCategorias = Categoria.objects.all()
    lstPlatos = Plato.objects.all()
    objNegocio = Negocio.objects.get(pk=1)

    
    request.session["negocio_telefono"] = objNegocio.telefono
    request.session["negocio_logo"] = objNegocio.imagen.url
    
   
    
    context = {
        'categorias': lstCategorias,
        'platos': lstPlatos,
    }
    return render(request,'menu.html',context)

def plato(request,plato_id):
    objPlato = Plato.objects.get(pk=plato_id)
    context = {
        'plato' : objPlato
    }
    
    return render(request,'plato.html',context)

from .carrito import Cart

def agregarCarrito(request,plato_id):
    objPlato = Plato.objects.get(pk=plato_id)
    cantidad = int(request.POST['cantidad'])
    carrito = Cart(request)
    carrito.add(objPlato,cantidad)
    print(request.session.get("cart"))
    return render(request,'carrito.html')

def mostrarCarrito(request):
    return render(request,'carrito.html')

def eliminarPlatoCarrito(request,plato_id):
    objPlato = Plato.objects.get(pk=plato_id)
    carrito = Cart(request)
    carrito.remove(objPlato)
    return redirect('/delivery/carrito')

def limpiarCarrito(request):
    carrito = Cart(request)
    carrito.clear()
    return redirect('/delivery/carrito')

from django.contrib.auth import authenticate,login,logout

def loginUsuario(request):
    context = {}
    
    if request.method == 'POST':
        dataUsuario = request.POST['usuario']
        dataClave = request.POST['clave']
        
        print(dataUsuario)
        
        
        
        loginUsuario  = authenticate(request,username=dataUsuario,password=dataClave)
        if loginUsuario is not None:
            login(request,loginUsuario)
            return redirect('/delivery/pedido')
        else:
            context = {
                'error':'datos incorrectos'
            }
        
    
    return render(request,'login.html',context)

from django.contrib.auth.models import User

def registroCliente(request):
    
    if request.method == 'POST':
        #registrar un nuevo cliente
        usuario = request.POST['usuario']
        clave = request.POST['password']
        
        nuevoUsuario = User.objects.create_user(username=usuario,password=clave)
        
        nuevoUsuario.first_name = request.POST['nombre']
        nuevoUsuario.last_name = request.POST['apellido']
        nuevoUsuario.email = request.POST['email']
        
        nuevoUsuario.save()
        
        nuevoCliente = Cliente(usuario=nuevoUsuario)
        nuevoCliente.telefono = request.POST['telefono']
        nuevoCliente.save()
        
        return redirect('/delivery/login')
    
    return render(request,'registro.html')

def registrarPedido(request):
   
    if request.user.id is not None:
        usuarioPedido = User.objects.get(pk=request.user.id)
        clientePedido = Cliente.objects.get(usuario=usuarioPedido)
        lstFormasPago = FormaPago.objects.all()
        context = {
            'nombres':request.user.first_name,
            'apellidos':request.user.last_name,
            'telefono':clientePedido.telefono,
            'email':request.user.email,
            'formaspago': lstFormasPago
            
        }
    else:
        return redirect('/delivery/login')
    
    
    return render(request,'pedido.html',context)

def confirmarPedido(request):
    #REGISTRO PEDIDO EN BASE DE DATOS
    print("ENVIANDO PEDIDO.....")
    usuarioPedido = User.objects.get(pk=request.user.id)
    clientePedido = Cliente.objects.get(usuario=usuarioPedido)
    dataFormaPagoId = request.POST['chkFormaPago']
    dataDireccion = request.POST['direccion']
            
    dataFormaPago = FormaPago.objects.get(pk=dataFormaPagoId)
            
    nuevoPedido = Pedido()
    nuevoPedido.cliente = clientePedido
    nuevoPedido.direccion = dataDireccion
    nuevoPedido.formaPago = dataFormaPago
    nuevoPedido.totalPagar = float(request.session.get("totalCart"))
    nuevoPedido.montoPago = 0
    nuevoPedido.save()
    
    #registramos detalle de pedido
    carritoPedido = request.session.get("cart")
    for key,value in carritoPedido.items():
        nuevoDetalle = PedidoDetalle()
        nuevoDetalle.pedido = nuevoPedido
        nuevoDetalle.cantidad = int(value["cantidad"])
        nuevoDetalle.precio = float(value["precio"])
        
        detallePlato = Plato.objects.get(pk=value["plato_id"])
        
        nuevoDetalle.plato = detallePlato
        nuevoDetalle.save()
    
    carrito = Cart(request)
    carrito.clear()
    return render(request,'gracias.html')
    
def gracias(request):
    return render(request,'gracias.html')

menuya/delivery/templates/carrito.html
{%extends 'layout.html' %}
{% block content %}

    <!-- cart area start -->
    <div class="cart-area pd-top-120 pd-bottom-120">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-12">
                    <div class="table-responsive mb-4">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th class="blank"></th>
                                    <th class="blank"></th>
                                    <th class="blank"></th>
                                    <th class="title-name">Plato</th>
                                    <th scope="col">Precio</th>
                                    <th scope="col">Cantidad</th>
                                    <th>Total</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for key,value in request.session.cart.items %}
                                    <tr>
                                        <td class="table-close-btn"><a href="{% url 'delivery:eliminarCarrito' value.plato_id %}"><i class="ri-close-line"></i></a></td>
                                        <th scope="row"><img src="{{ value.imagen }}" alt="img"></th>
                                        <td colspan="2" class="item-name">
                                            <div class="details">
                                                <h5>{{ value.nombre }}</h5>
                                            </div>
                                        </td>
                                        <td>S/. {{ value.precio }}</td>
                                        <td class="table-quantity">
                                            <form>
                                                <div class="quantity buttons_added">
                                                    <input type="button" value="-" class="minus">
                                                    <input type="number" class="input-text qty text" step="1" min="1" max="10000" name="cantidad" value="{{value.cantidad}}">
                                                    <input type="button" value="+" class="plus">
                                                </div>
                                            </form>
                                        </td>
                                        <td>S/. {{ value.total }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>                    
                </div>
                <div class="col-lg-8">
                    <div class="promotional-area">
                        <form class="default-form-wrap" action="{% url 'delivery:limpiarCarrito' %}">
                            <div class="row">
                                <div class="col-md-4 col-sm-6 text-md-end">
                                    <button type="submit" class="btn btn-base">LIMPIAR CARRITO</button>
                                </div>
                            </div>
                        </form>
                        <a class="btn btn-secondary w-100" href="/delivery"> AGREGAR MAS PLATOS</a>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="order-cart-area">
                        <div class="order-cart">
                            <h5>TOTAL</h5>
                            <ul>
                                <li class="total"><span>S/. {{ request.session.totalCart }}</span></li>
                            </ul>
                        </div>
                        <a class="btn btn-secondary w-100" href="{% url 'delivery:pedido' %}"> REALIZAR PEDIDO</a>
                    </div>                
                </div>
            </div>
        </div>
    </div>
    <!-- cart area end -->

{% endblock %}

menuya/delivery/templates/gracias.html
{% extends "layout.html" %}
{% block content %}
<section class="about-area pd-top-120">
    <div class="container">
        <h3 class="sub-title">GRACIAS POR TU PEDIDO</h3>
    </div>
</section>
{% endblock %}

menuya/delivery/templates/index.html
{% extends "layout.html" %}
{% block content %}
<section class="about-area pd-top-120">
    <div class="container">
        <h3 class="sub-title">BIENVENIDO</h3>
    </div>
</section>
{% endblock %}

menuya/delivery/templates/login.html
{% extends 'layout.html' %}
{% block content %}
<div class="checkout-area pd-top-120 pd-bottom-120">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-7">
                <div class="alert alert-danger" role="alert">
                    {{error}}
                  </div>
                <div class="bill-payment-wrap">
                    <h5>LOGIN DE USUARIO</h5>

                    <form class="default-form-wrap style-2" action="{% url 'delivery:login' %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6">
                                <label>Usuario</label>
                                <div class="single-input-wrap">
                                    <input type="text" name="usuario" class="form-control" placeholder="tu nombre de usuario">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label>Password</label>
                                <div class="single-input-wrap">
                                    <input type="Password" name="clave" class="form-control" placeholder="tu clave">
                                </div>
                            </div>
                            
                                 <input type="submit" class="btn btn-base" value="INICIAR SESIÓN">
                                 <a href="#" class="btn btn-base">CREAR CUENTA</a>
                            
                        </div>
                    </form>
                </div>                    
            </div>
            
        </div>
    </div>
</div>
{% endblock %}

menuya/delivery/templates/menu.html
{% extends "layout.html" %}
{% block content %}
{% load static %}
<!-- bredcrumb Area Start-->
<section class="breadcrumb-area">
    <div class="banner-bg-img"></div>
    <div class="banner-shape-1"><img src="{% static 'assets/img/banner/shape-1.png' %}" alt="img"></div>
    <div class="banner-shape-2"><img src="{% static 'assets/img/banner/shape-2.png' %}" alt="img"></div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 align-self-center">
                <div class="banner-inner text-center">
                    <h3>Seleccione su pedido
                    </h3>
                    <h1>NUESTRO MENU</h1>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- bredcrumb Area End -->

<!-- category Area Start-->
<section class="category-area">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-12 align-self-center">
                <ul class="category-menu">
                    {% for cat in categorias %}
                    <li class="category-wrap"><a href="shop.html"><img src="{{ cat.imagen.url }}" alt="category">{{ cat.nombre }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</section>
<!-- category Area End -->
<!-- populer Area Start-->
<section class="populer-area pd-top-50 pd-bottom-120">
    <div class="container">
        <div class="row justify-content-center">
        {% for p in platos %}
            <div class="col-lg-4 col-md-6">
                <div class="single-item-wrap">
                    <div class="thumb">
                        <img src="{{ p.imagen.url }}" alt="img">
                        <a class="fav-btn" href="#"><i class="ri-heart-line"></i></a>
                    </div>
                    <div class="wrap-details">
                        <h5><a href="single-product.html">{{ p.nombre }}</a></h5>
                        <div class="wrap-footer">
                            <h6 class="price">S/. {{ p.precio }} </h6>
                        </div>
                    </div>
                    <div class="btn-area">
                        <a class="btn btn-secondary" href="{% url 'delivery:plato' p.id %}">MAS INFO </a>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
</section>
<!-- populer Area End -->
{% endblock %}

menuya/delivery/templates/pedido.html
{% extends "layout.html" %}
{% block content %}
    <!-- checkout area start -->
    <div class="checkout-area pd-top-120 pd-bottom-120">

        <div class="container">
            <form class="default-form-wrap style-2" action="{% url 'delivery:confirmarPedido' %}" method="post">
                {% csrf_token %}
                <div class="row justify-content-center">
                    <div class="col-lg-7">
                        <div class="bill-payment-wrap">
                            <h5>PEDIDO
                            </h5>
                            
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Nombre</label>
                                        <div class="single-input-wrap">
                                            <input type="text" class="form-control" value="{{ nombres }}">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <label>Apellidos</label>
                                        <div class="single-input-wrap">
                                            <input type="text" class="form-control" value="{{ apellidos }}">
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <label>Dirección</label>
                                        <div class="single-input-wrap">
                                            <input type="text" name="direccion" class="form-control" placeholder="dirección de envio">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <label>Telefono</label>
                                        <div class="single-input-wrap">
                                            <input type="text" class="form-control" value="{{ telefono }}">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <label>Email</label>
                                        <div class="single-input-wrap">
                                            <input type="text" class="form-control" value="{{ email }}">
                                        </div>
                                    </div>
                                </div>
                        </div>                    
                    </div>
                    <div class="col-lg-5">
                        <div class="order-area">
                            <h5 class="title">Resumen de Pedido</h5>
                            <div class="order-product">
                                {% for key,value in request.session.cart.items %}
                                    <div class="thumb">
                                        <img src="{{ value.imagen }}" alt="img">
                                    </div>
                                    <div class="details">
                                        <h6>{{ value.nombre }}</h6>
                                    </div>
                                {% endfor %}
                            </div>
                            <ul class="amount">
                                <li class="total">Total<span>S/. {{ request.session.totalCart }}</span></li>
                            </ul>
                            <div class="peyment-method">
                                <h6>Formas de Pago</h6>
                                <ul class="card-area">
                                    {% for pago in formaspago %}
                                    <li>
                                        <div class="form-check">
                                            <input class="form-check-input" type="radio" name="chkFormaPago" id="flexRadioDefault1" value="{{pago.id}}">
                                            <label class="form-check-label" for="flexRadioDefault1">
                                            </label>
                                        </div>
                                        <div class="details">
                                            <h6>{{ pago.nombre }}</h6>
                    
                                        </div>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <input type="submit" value="CONFIRMAR PEDIDO " class="btn btn-secondary w-100"/>
                        </div>                
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- checkout area end -->
{% endblock %}

menuya/delivery/templates/plato.html
{% extends 'layout.html' %}
{% block content %}
<div class="shop-details-area pd-top-100">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="sticy-product">
                    <div class="product-thumbnail-wrapper">
                        <img src="{{ plato.imagen.url }}"/>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="shop-item-details">                       
                    <h2 class="entry-title">{{ plato.nombre }}</h2>
                    <div class="row">
                        <div class="col-lg-6 align-self-center">
                            <h4 class="price">S. {{ plato.precio }}</h4>
                        </div>                            
                    </div>   
                    <p class="mt-4">{{ plato.descripcion }}</p>    
                    <form action="{% url 'delivery:agregarCarrito' plato.id %}" method="post">
                        {% csrf_token %}
                        <div class="quantity buttons_added">
                            <input type="button" value="-" class="minus">
                            <input type="number" class="input-text qty text" step="1" min="1" max="10000" name="cantidad" value="1">
                            <input type="button" value="+" class="plus">
                        </div>
                        <button type="submit" class="btn btn-secondary">AGREGAR AL CARRITO</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

menuya/delivery/templates/registro.html
{% extends 'layout.html' %}
{% block content %}
<div class="checkout-area pd-top-120 pd-bottom-120">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-7">
                <div class="bill-payment-wrap">
                    <h5>REGISTRO DE NUEVO CLIENTE</h5>
                    <form class="default-form-wrap style-2" action="{% url 'delivery:registro' %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6">
                                <label>Usuario</label>
                                <div class="single-input-wrap">
                                    <input type="text" name="usuario" class="form-control" placeholder="tu nombre de usuario">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label>Password</label>
                                <div class="single-input-wrap">
                                    <input type="Password" name="password" class="form-control" placeholder="tu clave">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label>Nombres</label>
                                <div class="single-input-wrap">
                                    <input type="text" name="nombre" class="form-control" placeholder="Nombres">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label>Apellidos</label>
                                <div class="single-input-wrap">
                                    <input type="text" name="apellido" class="form-control" placeholder="Apellidos">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label>Telefono</label>
                                <div class="single-input-wrap">
                                    <input type="text" name="telefono" class="form-control" placeholder="Telefono">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label>Email</label>
                                <div class="single-input-wrap">
                                    <input type="text" name="email" class="form-control" placeholder="Email">
                                </div>
                            </div>
                            <input type="submit" class="btn btn-base" value="REGISTRAR DATOS">
                        </div>
                    </form>
                </div>                    
            </div>
            
        </div>
    </div>
</div>
{% endblock %}